server.port: 6001
spring.application.name: traincentral
eureka:
  client:
    serviceUrl:
      defaultZone: http://134.2.25.78:8761/eureka/

   
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        greetings-in:
          destination: trainupdate
          contentType: application/json
